language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
sudo: false
notifications:
    email: false
after_success:
    - julia -e 'using Pkg; Pkg.dir(pwd())); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
